import * as dotenv from 'dotenv';
dotenv.config();
import { S3Client, PutObjectCommand, DeleteObjectCommand, ListObjectsV2Command } from "@aws-sdk/client-s3";
import { TranscribeClient, StartTranscriptionJobCommand, GetTranscriptionJobCommand } from "@aws-sdk/client-transcribe";
import express from 'express';
import * as crypto from 'crypto';
import path from 'path';
import multer from 'multer';
import { EdgeTTS } from 'node-edge-tts';
import { GoogleGenAI, Type } from '@google/genai';
import fs from 'fs';
import os from 'os';
import { exec, spawn } from 'child_process';
import util from 'util';

const execAsync = util.promisify(exec);

function escapeFFmpegFilterPath(value: string): string {
  return value
    .replace(/\\/g, '/')
    .replace(/'/g, "\\'")
    .replace(/:/g, '\\:');
}

const KHMER_COMBINING_REGEX = /[\u17B4-\u17D3\u17DD]/;

function formatKhmerSubtitleText(text: string): string {
  if (!text) return '';
  const normalized = text.normalize('NFC');
  if (!/[\u1780-\u17FF]/.test(normalized)) return normalized;
  try {
    const clean = normalized.replace(/\u200B+/g, '');
    const segmenter = new Intl.Segmenter('km', { granularity: 'word' });
    const segments = [...segmenter.segment(clean)].map(s => s.segment);
    let result = '';
    for (let i = 0; i < segments.length; i++) {
      const seg = segments[i];
      result += seg;
      const next = segments[i + 1];
      if (
        next &&
        !/\s/.test(seg) &&
        !/\s/.test(next) &&
        !seg.endsWith('\u17D2') &&
        !KHMER_COMBINING_REGEX.test(next[0])
      ) {
        result += '\u200B';
      }
    }
    return result;
  } catch (e) {
    return normalized;
  }
}

function srtTimeToAssTime(srtTime: string): string {
  const clean = (srtTime || '').trim().replace(',', '.');
  const parts = clean.split(':');
  let h = 0, m = 0, s = 0;
  if (parts.length === 3) {
    h = parseInt(parts[0], 10) || 0;
    m = parseInt(parts[1], 10) || 0;
    s = parseFloat(parts[2]) || 0;
  } else if (parts.length === 2) {
    m = parseInt(parts[0], 10) || 0;
    s = parseFloat(parts[1]) || 0;
  } else {
    s = parseFloat(parts[0]) || 0;
  }
  const totalCs = Math.max(0, Math.round(s * 100));
  const secs = Math.floor(totalCs / 100);
  const cs = totalCs % 100;
  const mTotal = m + Math.floor(secs / 60);
  const finalSecs = secs % 60;
  const hTotal = h + Math.floor(mTotal / 60);
  const finalMins = mTotal % 60;
  return `${hTotal}:${String(finalMins).padStart(2, '0')}:${String(finalSecs).padStart(2, '0')}.${String(cs).padStart(2, '0')}`;
}

function convertSrtToAss(srtContent: string, width = 1280, height = 720): string {
  const isPortrait = height > width;
  const playResX = width || (isPortrait ? 720 : 1280);
  const playResY = height || (isPortrait ? 1280 : 720);
  const fontSize = isPortrait ? 44 : 38;
  const marginV = isPortrait ? 70 : 42;
  const marginLR = isPortrait ? 35 : 45;
  const outline = isPortrait ? 2.8 : 2.6;
  const shadow = isPortrait ? 1.2 : 1.0;

  const header = `[Script Info]
; Script generated by DubberAI
ScriptType: v4.00+
PlayResX: ${playResX}
PlayResY: ${playResY}
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Noto Sans Khmer,${fontSize},&H00FFFFFF,&H000000FF,&H00000000,&H80000000,1,0,0,0,100,100,0,0,1,${outline},${shadow},2,${marginLR},${marginLR},${marginV},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  const clean = srtContent.replace(/^\uFEFF/, '').replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const blocks = clean.split(/\n\s*\n/);
  const events: string[] = [];

  for (const block of blocks) {
    const lines = block.trim().split('\n').map(l => l.trim()).filter(Boolean);
    if (lines.length === 0) continue;

    let timeIndex = -1;
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].includes('-->')) {
        timeIndex = i;
        break;
      }
    }
    if (timeIndex === -1) continue;

    const [rawStart, rawEnd] = lines[timeIndex].split(/\s*-->\s*/);
    const startAss = srtTimeToAssTime(rawStart);
    const endAss = srtTimeToAssTime(rawEnd);

    const textLines = lines.slice(timeIndex + 1);
    if (textLines.length === 0) continue;

    const formattedText = textLines
      .map(line => formatKhmerSubtitleText(line).replace(/\{/g, '\\{').replace(/\}/g, '\\}'))
      .join('\\N');

    events.push(`Dialogue: 0,${startAss},${endAss},Default,,0,0,0,,${formattedText}`);
  }

  return header + events.join('\n') + '\n';
}

function buildSubtitleVideoFilter(srtPath: string): string {
  const fontsDir = path.resolve(process.cwd(), 'fonts');
  return (
    `subtitles='${escapeFFmpegFilterPath(srtPath)}':fontsdir='${fontsDir}'` +
    `:force_style='FontName=Noto Sans Khmer,FontSize=24,BorderStyle=1,Outline=2,Shadow=0,MarginV=40,MarginL=25,MarginR=25,WrapStyle=0'`
  );
}

function buildAssVideoFilter(assPath: string): string {
  const fontsDir = path.resolve(process.cwd(), 'fonts');
  return `ass='${escapeFFmpegFilterPath(assPath)}':fontsdir='${fontsDir}'`;
}

function logFfmpegDiagnostic(stepName, command, error, stderr, stdout) {
  const timestamp = new Date().toISOString();
  console.error(`\n[FFMPEG DIAGNOSTIC LOG - ${timestamp}]`);
  console.error(`STEP: ${stepName}`);
  console.error(`COMMAND: ${command}`);
  if (error) {
    console.error(`ERROR OBJECT: ${error.message || error}`);
  }
  if (stderr) {
    console.error(`STDERR:\n${stderr}`);
  }
  if (stdout) {
    console.error(`STDOUT:\n${stdout}`);
  }
  console.error(`[END FFMPEG DIAGNOSTIC]\n`);
}

const app = express();
const PORT = Number(process.env.PORT) || 3000;
const MAX_ALLOWED_TTS_OVERSPEECH = 0.25;
// Khmer TTS can be substantially longer than very short source subtitles.
// Allow auto-fitting up to 2.75x total tempo; FFmpeg's atempo filter is applied
// as a chain when the requested rate is above its single-filter limit of 2x.
const MAX_TTS_SPEED_INCREASE = 1.75;

app.use(express.json({ limit: '500mb' }));
app.use(express.urlencoded({ extended: true, limit: '500mb' }));

const upload = multer({ dest: os.tmpdir(), limits: { fileSize: 500 * 1024 * 1024 } });

type AudioSegmentMetadata = {
  key: string;
  start: string | number;
  end: string | number;
  segmentId?: string;
  speakerId?: string;
  voiceId?: string;
  expectedDuration?: number;
};

type RenderedAudioSegment = {
  key: string;
  path: string;
  metadata: AudioSegmentMetadata;
  startSeconds: number;
  endSeconds: number;
  sourceDuration: number;
  ttsDuration: number;
  placementSeconds: number;
  rate: number;
  sampleRate: number;
  channels: number;
  renderOrder: number;
};

type SubtitleLine = {
  id: string;
  start: string;
  end: string;
  text: string;
  gender?: 'female' | 'male';
  speaker?: string;
  speakerName?: string;
};

interface SpeakerVoiceProfile {
  id: string;
  name: string;
  gender: 'female' | 'male';
  voiceSource: 'video' | 'upload' | 'clean_ai';
  referenceAudioBase64?: string | null;
  audioPreviewUrl?: string | null;
  refText?: string;
  refStart?: number;
  refEnd?: number;
  videoTime?: string;
}

function parseTimestamp(value: string | number | undefined): number | null {
  if (typeof value === 'number') {
    return Number.isFinite(value) && value >= 0 ? value : null;
  }
  if (!value || typeof value !== 'string') return null;
  const parts = value.replace(',', '.').trim().split(':').map((part) => Number(part));
  if (parts.some((part) => !Number.isFinite(part))) return null;
  if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
  if (parts.length === 2) return parts[0] * 60 + parts[1];
  if (parts.length === 1) return parts[0];
  return null;
}

function formatSeconds(seconds: number): string {
  return seconds.toFixed(3);
}

function formatTimelineTimestamp(seconds: number): string {
  const rounded = Math.max(0, Math.round(seconds * 1000) / 1000);
  const hours = Math.floor(rounded / 3600);
  const minutes = Math.floor((rounded % 3600) / 60);
  const remaining = rounded % 60;
  return hours > 0
    ? `${hours}:${String(minutes).padStart(2, '0')}:${remaining.toFixed(3).padStart(6, '0')}`
    : `${minutes}:${remaining.toFixed(3).padStart(6, '0')}`;
}

function normalizeSubtitleTimeline(lines: any[]): any[] {
  return lines
    .map((line, index) => {
      const start = parseTimestamp(String(line?.start ?? ''));
      let end = parseTimestamp(String(line?.end ?? ''));
      if (start === null || start < 0) {
        console.warn(`[TIMELINE] Dropping subtitle ${index + 1}: invalid start timestamp`);
        return null;
      }
      if (end === null || end <= start || end - start < 0.2) {
        const nextStart = parseTimestamp(String(lines[index + 1]?.start ?? ''));
        end = nextStart !== null && nextStart > start ? nextStart : start + 0.75;
        console.warn(
          `[TIMELINE] Normalized subtitle ${index + 1} end to ${formatTimelineTimestamp(end)}`
        );
      }
      return {
        ...line,
        start: formatTimelineTimestamp(start),
        end: formatTimelineTimestamp(end)
      };
    })
    .filter(Boolean);
}

function buildAtempoFilter(rate: number): string {
  if (rate <= 1) return '';
  const filters: string[] = [];
  let remaining = rate;
  while (remaining > 2) {
    filters.push('atempo=2.0000');
    remaining /= 2;
  }
  if (remaining > 1.0001) {
    filters.push(`atempo=${remaining.toFixed(4)}`);
  }
  return filters.join(',');
}

function validateSubtitleLine(value: any, index: number): SubtitleLine {
  if (!value || typeof value !== 'object') {
    throw new Error(`Invalid subtitle entry at index ${index}`);
  }
  const id = typeof value.id === 'string' || typeof value.id === 'number'
    ? String(value.id)
    : '';
  if (!id) {
    throw new Error(`Invalid subtitle ID at index ${index}`);
  }
  if (typeof value.text !== 'string' || value.text.trim().length === 0) {
    throw new Error(`Invalid subtitle text at index ${index}`);
  }
  const startSeconds = parseTimestamp(value.start);
  const endSeconds = parseTimestamp(value.end);
  if (startSeconds === null || startSeconds < 0) {
    throw new Error(`Invalid start timestamp at subtitle index ${index}`);
  }
  if (endSeconds === null || endSeconds <= startSeconds) {
    throw new Error(
      `Invalid end timestamp at subtitle index ${index}: ` +
      `start=${String(value.start)} end=${String(value.end)}`
    );
  }
  const rawGender = typeof value.gender === 'string' ? value.gender.toLowerCase().trim() : '';
  let gender: 'female' | 'male' | undefined = undefined;
  if (rawGender.includes('female') || rawGender.includes('woman') || rawGender.includes('girl') || rawGender.includes('ស្រី')) {
    gender = 'female';
  } else if (rawGender.includes('male') || rawGender.includes('man') || rawGender.includes('boy') || rawGender.includes('ប្រុស')) {
    gender = 'male';
  }

  const rawSpeaker = typeof value.speaker === 'string' ? value.speaker.trim() : (typeof value.speakerId === 'string' ? value.speakerId.trim() : '');
  const rawSpeakerName = typeof value.speakerName === 'string' ? value.speakerName.trim() : '';
  const speaker = rawSpeaker || (gender === 'female' ? 'speaker_001' : 'speaker_002');
  const speakerName = rawSpeakerName || (gender === 'female' ? 'Speaker 1 (ស្រី)' : 'Speaker 2 (ប្រុស)');

  return {
    id,
    start: String(value.start),
    end: String(value.end),
    text: value.text.trim(),
    ...(gender ? { gender } : {}),
    speaker,
    speakerName
  };
}

function validateExportAudioMetadata(value: any): AudioSegmentMetadata[] {
  if (!Array.isArray(value)) {
    throw new Error('Export audio metadata must be a JSON array');
  }
  const keys = new Set<string>();
  return value.map((item: any, index: number) => {
    if (!item || typeof item !== 'object') {
      throw new Error(`Invalid export audio metadata entry at index ${index}`);
    }
    if (typeof item.key !== 'string' || !/^audio_\d+$/.test(item.key)) {
      throw new Error(`Invalid audio metadata key at index ${index}`);
    }
    if (keys.has(item.key)) {
      throw new Error(`Duplicate audio metadata key: ${item.key}`);
    }
    keys.add(item.key);

    const startSeconds = parseTimestamp(item.start);
    const endSeconds = parseTimestamp(item.end);
    if (startSeconds === null || startSeconds < 0) {
      throw new Error(`Invalid start timestamp for ${item.key}`);
    }
    if (endSeconds === null || endSeconds <= startSeconds) {
      throw new Error(`Invalid end timestamp for ${item.key}`);
    }
    if (item.segmentId !== undefined && (typeof item.segmentId !== 'string' || !item.segmentId)) {
      throw new Error(`Invalid segment ID for ${item.key}`);
    }
    if (
      item.expectedDuration !== undefined &&
      (!Number.isFinite(Number(item.expectedDuration)) || Number(item.expectedDuration) <= 0)
    ) {
      throw new Error(`Invalid expected TTS duration for ${item.key}`);
    }

    return {
      ...item,
      start: String(item.start),
      end: String(item.end)
    };
  });
}

function buildFinalAudioMap(
  hasOriginalAudio: boolean,
  renderedSegments: RenderedAudioSegment[]
): string {
  if (renderedSegments.length > 0) return '1:a';
  return hasOriginalAudio ? '0:a' : '';
}

function validateSubtitleLines(lines: any): SubtitleLine[] {
  if (!Array.isArray(lines) || lines.length === 0) {
    throw new Error('Subtitle lines must be a non-empty array');
  }
  return lines.map(validateSubtitleLine);
}

function mergeTranslatedSubtitleLine(
  originalLine: SubtitleLine,
  translation: any,
  index: number
): SubtitleLine {
  const text =
    typeof translation?.text === 'string'
      ? translation.text.trim()
      : typeof translation?.Text === 'string'
        ? translation.Text.trim()
        : '';
  if (!text) {
    throw new Error(`Empty translation at subtitle index ${index}`);
  }

  const rawGender = typeof translation?.gender === 'string' ? translation.gender.toLowerCase().trim() : '';
  let gender: 'female' | 'male' | undefined = originalLine.gender;
  if (rawGender.includes('female') || rawGender.includes('ស្រី')) gender = 'female';
  else if (rawGender.includes('male') || rawGender.includes('ប្រុស')) gender = 'male';

  const speaker = typeof translation?.speaker === 'string' && translation.speaker.trim()
    ? translation.speaker.trim()
    : (originalLine.speaker || (gender === 'female' ? 'speaker_001' : 'speaker_002'));

  const speakerName = typeof translation?.speakerName === 'string' && translation.speakerName.trim()
    ? translation.speakerName.trim()
    : (originalLine.speakerName || (gender === 'female' ? 'Speaker 1 (ស្រី)' : 'Speaker 2 (ប្រុស)'));

  return {
    id: originalLine.id,
    start: originalLine.start,
    end: originalLine.end,
    text,
    ...(gender ? { gender } : {}),
    speaker,
    speakerName
  };
}

async function probeAudio(path: string): Promise<{ duration: number; sampleRate: number; channels: number }> {
  const command = `ffprobe -v error -show_entries stream=sample_rate,channels -show_entries format=duration -of json "${path}"`;
  const { stdout } = await execAsync(command);
  const parsed = JSON.parse(stdout);
  const duration = Number(parsed?.format?.duration);
  const sampleRate = Number(parsed?.streams?.[0]?.sample_rate);
  const channels = Number(parsed?.streams?.[0]?.channels);
  if (!Number.isFinite(duration) || duration <= 0 ||
      !Number.isFinite(sampleRate) || sampleRate <= 0 ||
      !Number.isFinite(channels) || channels <= 0) {
    throw new Error(`Invalid audio metadata for ${path}`);
  }
  return { duration, sampleRate, channels };
}

async function buildRenderedAudioSegments(
  files: Express.Multer.File[],
  metadata: AudioSegmentMetadata[],
  videoDuration?: number
): Promise<RenderedAudioSegment[]> {
  const audioFiles = files
    .filter((file) => file.fieldname.startsWith('audio_'))
    .map((file) => ({ file, stat: fs.statSync(file.path) }))
    .filter(({ file, stat }) => stat.isFile() && stat.size > 100)
    .sort((a, b) => a.file.fieldname.localeCompare(b.file.fieldname, 'en', { numeric: true }));

  const metadataByKey = new Map<string, AudioSegmentMetadata>();
  for (const item of metadata) {
    if (!item || typeof item.key !== 'string' || !item.key.startsWith('audio_')) {
      throw new Error('Invalid audio metadata entry');
    }
    if (metadataByKey.has(item.key)) {
      throw new Error(`Duplicate audio metadata key: ${item.key}`);
    }
    metadataByKey.set(item.key, item);
  }

  const audioKeys = new Set(audioFiles.map(({ file }) => file.fieldname));
  const missingAudio = metadata.filter((item) => !audioKeys.has(item.key)).map((item) => item.key);
  if (missingAudio.length > 0) {
    throw new Error(`Missing TTS audio files: ${missingAudio.join(', ')}`);
  }
  const extraAudio = [...audioKeys].filter((key) => !metadataByKey.has(key));
  if (extraAudio.length > 0) {
    throw new Error(`TTS audio files without timeline metadata: ${extraAudio.join(', ')}`);
  }

  const segmentIds = new Set<string>();
  const renderedSegments: RenderedAudioSegment[] = [];
  for (let index = 0; index < audioFiles.length; index++) {
    const { file } = audioFiles[index];
    const item = metadataByKey.get(file.fieldname);
    const startSeconds = parseTimestamp(item?.start);
    const endSeconds = parseTimestamp(item?.end);
    if (startSeconds === null || startSeconds < 0) {
      throw new Error(`Invalid start timestamp for ${file.fieldname}`);
    }
    if (endSeconds === null || endSeconds <= startSeconds) {
      throw new Error(`Invalid end timestamp for ${file.fieldname}`);
    }
    const sourceDuration = endSeconds - startSeconds;
    if (item?.segmentId !== undefined) {
      if (typeof item.segmentId !== 'string' || item.segmentId.length === 0) {
        throw new Error(`Invalid segment ID for ${file.fieldname}`);
      }
      if (segmentIds.has(item.segmentId)) {
        throw new Error(`Duplicate segment ID: ${item.segmentId}`);
      }
      segmentIds.add(item.segmentId);
    }

    const probed = await probeAudio(file.path);
    if (item?.expectedDuration !== undefined) {
      const expectedDuration = Number(item.expectedDuration);
      if (Number.isFinite(expectedDuration) && Math.abs(expectedDuration - probed.duration) > 1.5) {
        console.warn(`[TIMELINE] Duration difference for ${file.fieldname}: expected=${expectedDuration.toFixed(2)}s probed=${probed.duration.toFixed(2)}s`);
      }
    }

    const nextStarts = metadata
      .map((m) => parseTimestamp(m?.start))
      .filter((s): s is number => s !== null && s > startSeconds)
      .sort((a, b) => a - b);

    let availableDuration = sourceDuration + MAX_ALLOWED_TTS_OVERSPEECH;
    if (nextStarts.length > 0) {
      const gapToNext = nextStarts[0] - startSeconds;
      const availableFromGap = Math.max(sourceDuration, gapToNext - 0.05);
      availableDuration = Math.max(availableDuration, availableFromGap);
    } else if (videoDuration !== undefined && videoDuration > startSeconds) {
      const gapToEnd = Math.max(sourceDuration, videoDuration - startSeconds - 0.05);
      availableDuration = Math.max(availableDuration, gapToEnd);
    }
    availableDuration = Math.max(0.2, availableDuration);

    if (probed.duration <= availableDuration) {
      renderedSegments.push({
        key: file.fieldname,
        path: file.path,
        metadata: item!,
        startSeconds,
        endSeconds,
        sourceDuration,
        ttsDuration: probed.duration,
        placementSeconds: startSeconds,
        rate: 1,
        sampleRate: probed.sampleRate,
        channels: probed.channels,
        renderOrder: index + 1
      });
      continue;
    }

    // Adaptively calculate speed increase up to 3.5x using chained atempo filters.
    // Never fail or throw an unhandled error so export always finishes smoothly.
    const neededRate = probed.duration / availableDuration;
    const rate = Math.min(3.5, Math.max(1.0, neededRate));
    if (neededRate > 3.5) {
      console.warn(
        `[TIMELINE] TTS audio for ${file.fieldname} (${probed.duration.toFixed(2)}s) exceeds available time (${availableDuration.toFixed(2)}s). Capping rate at 3.5x.`
      );
    }

    renderedSegments.push({
      key: file.fieldname,
      path: file.path,
      metadata: item!,
      startSeconds,
      endSeconds,
      sourceDuration,
      ttsDuration: probed.duration / rate,
      placementSeconds: startSeconds,
      rate,
      sampleRate: probed.sampleRate,
      channels: probed.channels,
      renderOrder: index + 1
    });
  }
  return renderedSegments;
}

function validateSegmentTimeline(
  segments: RenderedAudioSegment[],
  videoDuration: number
): void {
  for (const segment of segments) {
    if (segment.endSeconds > videoDuration + 0.25) {
      console.warn(`[TIMELINE] Segment ${segment.key} ends after the video (${segment.endSeconds.toFixed(2)}s > ${videoDuration.toFixed(2)}s)`);
    }
    if (segment.placementSeconds < 0) {
      segment.placementSeconds = 0;
    }
  }

  const sorted = [...segments].sort((a, b) => a.startSeconds - b.startSeconds);
  for (let index = 0; index < sorted.length; index++) {
    const current = sorted[index];
    for (let nextIndex = index + 1; nextIndex < sorted.length; nextIndex++) {
      const next = sorted[nextIndex];
      const overlap = current.placementSeconds + current.ttsDuration - next.placementSeconds;
      const sourceTimingOverlaps =
        current.placementSeconds < next.endSeconds &&
        next.placementSeconds < current.endSeconds;
      if (overlap > 0.1 && sourceTimingOverlaps) {
        console.warn(
          `[TIMELINE] Non-blocking overlap: ${current.key} overlaps ${next.key} by ${formatSeconds(overlap)}s (amix will mix both seamlessly)`
        );
      }
      if (next.startSeconds >= current.endSeconds) break;
    }
  }
}

const defaultGeminiKey = process.env.GEMINI_API_KEY;
const ai = defaultGeminiKey ? new GoogleGenAI({ apiKey: defaultGeminiKey }) : null;

app.post('/api/upload-chunk', express.raw({ type: '*/*', limit: '500mb' }), async (req, res) => {
  try {
    const { fileId, chunkIndex } = req.query;
    if (!req.body || req.body.length === 0) {
      return res.status(400).json({ error: 'No chunk body provided' });
    }
    if (!fileId) {
      return res.status(400).json({ error: 'Missing fileId in query' });
    }
    const chunkPath = path.join(os.tmpdir(), `upload_${fileId}_part_${chunkIndex}`);
    fs.writeFileSync(chunkPath, req.body);
    res.json({ success: true });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

const jobs = new Map<string, {
  status: string,
  progress: number,
  lines?: any[],
  error?: string,
  masterVoiceBase64?: string | null,
  masterVoices?: { female?: string | null; male?: string | null },
  speakers?: Record<string, SpeakerVoiceProfile>
}>();

// Global token usage tracker — accumulates across all Gemini API calls per session
const tokenUsageTracker = {
  totalPromptTokens: 0,
  totalCandidatesTokens: 0,
  totalTokens: 0,
  callCount: 0,
  lastModel: '',
  lastUpdated: null as string | null,
  history: [] as Array<{
    model: string;
    promptTokens: number;
    candidatesTokens: number;
    totalTokens: number;
    timestamp: string;
  }>
};

function trackTokenUsage(model: string, usageMetadata: any) {
  if (!usageMetadata) return;
  const promptTokens = usageMetadata.promptTokenCount || 0;
  const candidatesTokens = usageMetadata.candidatesTokenCount || 0;
  const totalTokens = usageMetadata.totalTokenCount || (promptTokens + candidatesTokens);
  tokenUsageTracker.totalPromptTokens += promptTokens;
  tokenUsageTracker.totalCandidatesTokens += candidatesTokens;
  tokenUsageTracker.totalTokens += totalTokens;
  tokenUsageTracker.callCount += 1;
  tokenUsageTracker.lastModel = model;
  tokenUsageTracker.lastUpdated = new Date().toISOString();
  tokenUsageTracker.history.push({
    model,
    promptTokens,
    candidatesTokens,
    totalTokens,
    timestamp: new Date().toISOString()
  });
  // Keep only last 100 entries
  if (tokenUsageTracker.history.length > 100) {
    tokenUsageTracker.history = tokenUsageTracker.history.slice(-100);
  }
  console.log(`[Token Usage] model=${model} prompt=${promptTokens} candidates=${candidatesTokens} total=${totalTokens} | cumulative=${tokenUsageTracker.totalTokens}`);
}
const exportJobs = new Map<string, { status: string; error?: string; path?: string; progress?: number; }>();
const exportCache = new Map<string, string>();
const masterVoiceCache = new Map<string, string>();
const femaleVoiceCache = new Map<string, string>();
const maleVoiceCache = new Map<string, string>();
const speakerVoiceCache = new Map<string, string>(); // `${fileId}_${speakerId}` -> base64
const speakerProfileCache = new Map<string, Record<string, SpeakerVoiceProfile>>(); // `${fileId}` -> Record<string, SpeakerVoiceProfile>
const uploadedVideos = new Map<string, number>();

async function extractSpeakerReferenceVoices(
  filePath: string,
  fileId: string,
  lines: SubtitleLine[]
): Promise<Record<string, SpeakerVoiceProfile>> {
  const result: Record<string, SpeakerVoiceProfile> = {};
  if (!fs.existsSync(filePath) || !Array.isArray(lines) || lines.length === 0) return result;

  // 1. Group candidate lines by speakerId
  const speakerGroups = new Map<string, SubtitleLine[]>();
  for (const line of lines) {
    const spkId = line.speaker || (line.gender === 'female' ? 'speaker_001' : 'speaker_002');
    if (!speakerGroups.has(spkId)) {
      speakerGroups.set(spkId, []);
    }
    speakerGroups.get(spkId)!.push(line);
  }

  // 2. For each speaker, extract the cleanest candidate line
  for (const [spkId, spkLines] of speakerGroups.entries()) {
    const spkGender: 'female' | 'male' = spkLines.find(l => l.gender)?.gender || (spkId.endsWith('1') ? 'female' : 'male');
    const defaultName = spkLines[0]?.speakerName || (spkGender === 'female' ? `Speaker ${spkId.replace('speaker_', '')} (ស្រី)` : `Speaker ${spkId.replace('speaker_', '')} (ប្រុស)`);

    const validCandidates = spkLines
      .map(l => {
        const s = parseTimestamp(l.start);
        const e = parseTimestamp(l.end);
        if (s === null || e === null || e <= s) return null;
        return { start: s, end: e, duration: e - s, text: l.text };
      })
      .filter((c): c is { start: number; end: number; duration: number; text: string } => c !== null && c.duration >= 1.8)
      .slice(0, 10);

    let bestCandidate: { start: number; dur: number; text: string } | null = null;
    let highestPeak = -999;

    for (const cand of validCandidates) {
      const testStart = Math.max(0, cand.start);
      const testDur = Math.min(5.5, Math.max(2.5, cand.duration));
      const testTmp = path.join(os.tmpdir(), `test_${spkId}_${crypto.randomUUID()}.wav`);
      try {
        await execAsync(
          `ffmpeg -hide_banner -loglevel error -y -ss ${testStart.toFixed(2)} -t ${testDur.toFixed(2)} -i "${filePath}" -vn -acodec pcm_s16le -ar 16000 -ac 1 "${testTmp}"`
        );
        if (fs.existsSync(testTmp) && fs.statSync(testTmp).size > 2000) {
          const { stdout, stderr } = await execAsync(
            `ffmpeg -hide_banner -i "${testTmp}" -af "volumedetect" -f null -`
          );
          const out = (stderr || '') + (stdout || '');
          const maxMatch = out.match(/max_volume:\s*(-?[\d.]+)\s*dB/);
          const maxVol = maxMatch ? parseFloat(maxMatch[1]) : -99;
          if (maxVol > highestPeak) {
            highestPeak = maxVol;
            bestCandidate = { start: testStart, dur: testDur, text: cand.text };
          }
          if (maxVol > -13) {
            try { fs.unlinkSync(testTmp); } catch(e) {}
            break;
          }
        }
      } catch (e) {
      } finally {
        if (fs.existsSync(testTmp)) {
          try { fs.unlinkSync(testTmp); } catch(e) {}
        }
      }
    }

    let b64: string | null = null;
    let timeStr: string | undefined = undefined;

    if (bestCandidate) {
      const outPath = path.join(os.tmpdir(), `ref_voice_${fileId}_${spkId}.wav`);
      try {
        await execAsync(
          `ffmpeg -hide_banner -loglevel error -y -ss ${bestCandidate.start.toFixed(2)} -t ${bestCandidate.dur.toFixed(2)} -i "${filePath}" -vn -af "loudnorm=I=-16:TP=-1.5:LRA=11,silenceremove=start_periods=1:start_duration=0.05:start_threshold=-40dB" -acodec pcm_s16le -ar 16000 -ac 1 "${outPath}"`
        );
        if (fs.existsSync(outPath) && fs.statSync(outPath).size > 1500) {
          b64 = fs.readFileSync(outPath).toString('base64');
          speakerVoiceCache.set(`${fileId}_${spkId}`, b64);
          timeStr = formatTimelineTimestamp(bestCandidate.start);
          console.log(`[SPEAKER VOICE] Extracted ${spkId} (${defaultName}) at ${bestCandidate.start.toFixed(2)}s (dur=${bestCandidate.dur.toFixed(2)}s, peak=${highestPeak.toFixed(1)}dB)`);
        }
      } catch (err) {
        console.warn(`[SPEAKER VOICE] Extraction failed for ${spkId}:`, err);
      }
    }

    result[spkId] = {
      id: spkId,
      name: defaultName,
      gender: spkGender,
      voiceSource: b64 ? 'video' : 'clean_ai',
      referenceAudioBase64: b64,
      audioPreviewUrl: b64 ? `data:audio/wav;base64,${b64}` : null,
      refText: bestCandidate?.text,
      refStart: bestCandidate?.start,
      refEnd: bestCandidate ? (bestCandidate.start + bestCandidate.dur) : undefined,
      videoTime: timeStr
    };

    if (b64) {
      if (spkGender === 'female' && !femaleVoiceCache.has(fileId)) {
        femaleVoiceCache.set(fileId, b64);
      } else if (spkGender === 'male' && !maleVoiceCache.has(fileId)) {
        maleVoiceCache.set(fileId, b64);
      }
    }
  }

  speakerProfileCache.set(fileId, result);
  return result;
}

async function extractCharacterVoices(
  filePath: string,
  fileId: string,
  lines: SubtitleLine[]
): Promise<{ female: string | null; male: string | null }> {
  const speakers = await extractSpeakerReferenceVoices(filePath, fileId, lines);
  const femaleSpk = Object.values(speakers).find(s => s.gender === 'female' && s.referenceAudioBase64);
  const maleSpk = Object.values(speakers).find(s => s.gender === 'male' && s.referenceAudioBase64);
  return {
    female: femaleSpk?.referenceAudioBase64 || femaleVoiceCache.get(fileId) || null,
    male: maleSpk?.referenceAudioBase64 || maleVoiceCache.get(fileId) || null
  };
}

function trackUploadedVideo(fileId: string) {
  if (!fileId) return;
  uploadedVideos.set(fileId, Date.now());
  const twoHoursAgo = Date.now() - 2 * 60 * 60 * 1000;
  for (const [id, time] of uploadedVideos.entries()) {
    if (time < twoHoursAgo) {
      try {
        const oldPath = path.join(os.tmpdir(), `upload_${id}`);
        if (fs.existsSync(oldPath)) fs.unlinkSync(oldPath);
      } catch (e) {}
      uploadedVideos.delete(id);
    }
  }
}

app.get('/api/video-exists', (req, res) => {
  const fileId = req.query.fileId as string;
  if (!fileId) return res.json({ exists: false });
  const videoPath = path.join(os.tmpdir(), `upload_${fileId}`);
  const exists = fs.existsSync(videoPath) && fs.statSync(videoPath).size > 0;
  if (exists) {
    trackUploadedVideo(fileId);
  }
  res.json({ exists });
});

const handleExtractVoice = async (req: any, res: any) => {
  try {
    const { fileId, speakerId, charId, startTime, duration = 4.0 } = req.body;
    if (!fileId) {
      return res.status(400).json({ error: 'fileId is required' });
    }
    let mediaPath = path.join(os.tmpdir(), `upload_${fileId}`);
    if (!fs.existsSync(mediaPath)) {
      const audioPath = path.join(os.tmpdir(), `audio_${fileId}.mp3`);
      if (fs.existsSync(audioPath)) {
        mediaPath = audioPath;
      }
    }
    if (!fs.existsSync(mediaPath)) {
      const part0 = path.join(os.tmpdir(), `upload_${fileId}_part_0`);
      if (fs.existsSync(part0)) {
        let i = 0;
        const assembled = fs.createWriteStream(mediaPath);
        while (fs.existsSync(path.join(os.tmpdir(), `upload_${fileId}_part_${i}`))) {
          const chunkData = fs.readFileSync(path.join(os.tmpdir(), `upload_${fileId}_part_${i}`));
          assembled.write(chunkData);
          i++;
        }
        assembled.end();
      }
    }

    if (!fs.existsSync(mediaPath)) {
      return res.status(404).json({ error: 'រកមិនឃើញវីដេអូដើមលើម៉ាស៊ីនមេទេ។ សូមជ្រើសរើសបញ្ចូលឯកសារសំឡេង (Upload Audio) ជំនួសវិញ។' });
    }

    const sStart = Math.max(0, typeof startTime === 'number' ? startTime : (parseTimestamp(startTime) ?? 0));
    const sDur = Math.max(1.5, Math.min(8.0, Number(duration) || 4.0));
    const outWav = path.join(os.tmpdir(), `char_${crypto.randomUUID()}.wav`);

    await execAsync(
      `ffmpeg -hide_banner -loglevel error -y -ss ${sStart.toFixed(2)} -t ${sDur.toFixed(2)} -i "${mediaPath}" -vn -af "loudnorm=I=-16:TP=-1.5:LRA=11,silenceremove=start_periods=1:start_duration=0.05:start_threshold=-40dB" -acodec pcm_s16le -ar 16000 -ac 1 "${outWav}"`
    );

    if (!fs.existsSync(outWav) || fs.statSync(outWav).size < 1000) {
      return res.status(400).json({ error: 'កាត់សំឡេងមិនបានសម្រេច។ សូមសាកល្បងវិនាទីផ្សេងទៀត។' });
    }

    const audioBase64 = fs.readFileSync(outWav).toString('base64');
    const spkKey = speakerId || charId;
    if (spkKey) {
      speakerVoiceCache.set(`${fileId}_${spkKey}`, audioBase64);
    }
    try { fs.unlinkSync(outWav); } catch (e) {}

    return res.json({
      success: true,
      speakerId: spkKey,
      audioBase64,
      startTime: sStart,
      duration: sDur
    });
  } catch (err: any) {
    console.error('[EXTRACT-VOICE] Error:', err);
    res.status(500).json({ error: err.message || 'Extract character voice failed' });
  }
};

app.post('/api/extract-character-voice', handleExtractVoice);
app.post('/api/extract-speaker-voice', handleExtractVoice);


// ============================================================
// SHARED GEMINI SUBTITLE TRANSLATOR
// ============================================================
// IMPORTANT:
// - Receives an already-created source SRT
// - Translates ONLY the text field
// - NEVER changes id/start/end
// - NEVER changes subtitle line count
// ============================================================

async function translateSubtitleLinesToKhmer(
  currentAi: GoogleGenAI,
  sourceLines: any[],
  geminiModel: string
): Promise<any[]> {
  if (!Array.isArray(sourceLines) || sourceLines.length === 0) {
    throw new Error('No source subtitle lines available for translation.');
  }

  const CHUNK_SIZE = 40;
  const translatedLines: any[] = [];

  console.log(
    `[TRANSLATE] Translating ${sourceLines.length} subtitle lines using ${geminiModel}`
  );

  for (let i = 0; i < sourceLines.length; i += CHUNK_SIZE) {
    const chunk = sourceLines.slice(i, i + CHUNK_SIZE);

    let success = false;
    let retries = 0;
    let lastError: any = null;

    while (!success && retries < 3) {
      try {
        const response =
          await currentAi.models.generateContent({
            model: geminiModel,
            contents: [{
              role: 'user',
              parts: [{
                text:
`You are a professional subtitle translator.

Translate the following subtitle JSON array into Khmer (Cambodian).

STRICT RULES:

1. Translate ONLY the "text" field.
2. NEVER change "id".
3. NEVER change "start".
4. NEVER change "end".
5. Return EXACTLY the same number of subtitle objects.
6. Keep the EXACT same object order.
7. Do NOT merge subtitle lines.
8. Do NOT split subtitle lines.
9. Do NOT omit any subtitle.
10. Do NOT add any subtitle.
11. Preserve the original meaning accurately.
12. Do not summarize.
13. Do not invent information.
14. ALL translated "text" values must be Khmer.
15. Return ONLY valid JSON.
16. The output must contain exactly the same structure.

SOURCE SUBTITLES:
${JSON.stringify(chunk)}`
              }]
            }],
            config: {
              responseMimeType: 'application/json',
              responseSchema: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    id: { type: Type.STRING },
                    start: { type: Type.STRING },
                    end: { type: Type.STRING },
                    text: { type: Type.STRING },
                    gender: { type: Type.STRING },
                    speaker: { type: Type.STRING },
                    speakerName: { type: Type.STRING }
                  },
                  required: [
                    "id",
                    "start",
                    "end",
                    "text"
                  ]
                }
              }
            }
          });

        let responseText = response.text || '';
        trackTokenUsage(geminiModel, response.usageMetadata);

        responseText = responseText
          .replace(/^\s*```json\s*/, '')
          .replace(/\s*```\s*$/, '')
          .trim();

        const parsed = JSON.parse(responseText);

        if (!Array.isArray(parsed)) {
          throw new Error('Gemini translation response is not an array.');
        }

        if (parsed.length !== chunk.length) {
          throw new Error(
            `Gemini returned ${parsed.length} lines, expected ${chunk.length}.`
          );
        }

      const validated = chunk.map((originalLine: any, index: number) => {
          return mergeTranslatedSubtitleLine(
            validateSubtitleLine(originalLine, index),
            parsed[index],
            index
          );
        });

        translatedLines.push(...validated);
        success = true;

        console.log(
          `[TRANSLATE] Chunk ${i + 1}-${Math.min(i + CHUNK_SIZE, sourceLines.length)} completed`
        );

      } catch (err: any) {
        lastError = err;

        console.error(
          `[TRANSLATE] Chunk ${i} error:`,
          err?.message || err
        );

        retries++;

        if (retries < 3) {
          await new Promise(r => setTimeout(r, 3000));
        }
      }
    }

    if (!success) {
      throw new Error(
        'Translation via Gemini failed after 3 attempts: ' +
        (lastError?.message || lastError)
      );
    }
  }

  if (translatedLines.length !== sourceLines.length) {
    throw new Error(
      `Translation line count mismatch: ${translatedLines.length} / ${sourceLines.length}`
    );
  }

  return translatedLines;
}

app.post('/api/transcribe/start', async (req, res) => {
  const { fileId, mimetype, model, workflow, totalChunks } = req.body;
  const apiKey = req.headers['x-api-key'] as string; // Optional user key from headers
  const reqAwsAccessKeyId = req.headers['x-aws-access-key-id'] as string;
  const reqAwsSecretAccessKey = req.headers['x-aws-secret-access-key'] as string;
  const reqAwsRegion = req.headers['x-aws-region'] as string;
  const reqAwsS3Bucket = req.headers['x-aws-s3-bucket'] as string;
  const jobId = Date.now().toString();
  
  jobs.set(jobId, { status: 'starting', progress: 40 });
  res.json({ jobId });

  // Process in background to avoid HTTP timeouts
  (async () => {
    try {
      const filePath = path.join(os.tmpdir(), `upload_${fileId}`);
      
      // Merge chunks
      if (fs.existsSync(filePath)) {
         fs.unlinkSync(filePath);
      }
      for (let i = 0; i < (totalChunks || 0); i++) {
        const chunkPath = path.join(os.tmpdir(), `upload_${fileId}_part_${i}`);
        if (!fs.existsSync(chunkPath)) {
          throw new Error(`Missing chunk ${i}`);
        }
        const chunkData = fs.readFileSync(chunkPath);
        fs.appendFileSync(filePath, chunkData);
        fs.unlinkSync(chunkPath);
      }
      
      if (!fs.existsSync(filePath)) {
         throw new Error('File not found on server');
      }

      const currentAi = apiKey
          ? new GoogleGenAI({ apiKey })
          : ai;

        if (!currentAi) {
          throw new Error(
            'Gemini API Key មិនត្រូវបានកំណត់។ សូមបញ្ចូល Gemini API Key ក្នុង App Settings។'
          );
        }
      
      let uploadPath = filePath;
      let uploadMime = mimetype;
      
      const isVideo = mimetype.startsWith('video/') || mimetype === 'application/octet-stream' || mimetype === '';
      
      if (isVideo) {
        console.log('Extracting audio from video to speed up upload...');
        jobs.set(jobId, { status: 'extracting audio', progress: 42 });
        const audioPath = path.join(os.tmpdir(), `audio_${fileId}.mp3`);
        await execAsync(`ffmpeg -hide_banner -loglevel error -i "${filePath}" -vn -acodec libmp3lame -q:a 2 "${audioPath}" -y`);
        uploadPath = audioPath;
        uploadMime = 'audio/mpeg';
      }

      const activeWorkflow =
      workflow ||
      (model === 'amazon'
        ? 'amazon'
        : model === 'qwen-khmer'
          ? 'qwen-khmer'
          : 'gemini');

    const activeGeminiModel =
      model &&
      !['amazon'].includes(model)
        ? model
        : 'gemini-2.5-flash';

    const activeModel = activeWorkflow;

if (activeModel === 'amazon') {
         jobs.set(jobId, { status: 'uploading to s3', progress: 45 });
         console.log(`Uploading file to S3... ${uploadPath}`);
         
         const region = reqAwsRegion || process.env.AWS_REGION || 'ap-southeast-2';
         const bucket = reqAwsS3Bucket || process.env.AWS_S3_BUCKET || 'elasticbeanstalk-ap-southeast-2-824353504213';
         
         const awsConfig = {
           region,
           credentials: {
             accessKeyId: reqAwsAccessKeyId || process.env.AWS_ACCESS_KEY_ID || '',
             secretAccessKey: reqAwsSecretAccessKey || process.env.AWS_SECRET_ACCESS_KEY || ''
           }
         };
         
         if (!awsConfig.credentials.accessKeyId) {
             throw new Error("ការកំណត់ AWS Credentials មិនទាន់បានបំពេញ (AWS_ACCESS_KEY_ID នៅក្នុងកូដម៉ាស៊ីន)។");
         }
         
         const s3Client = new S3Client(awsConfig);
         const transcribeClient = new TranscribeClient(awsConfig);
         
         const s3Key = `uploads/${jobId}_audio.mp3`;
         const uploadStream = fs.createReadStream(uploadPath);
         
         await s3Client.send(new PutObjectCommand({
             Bucket: bucket,
             Key: s3Key,
             Body: uploadStream
         }));
         
         jobs.set(jobId, { status: 'transcribing with amazon', progress: 50 });
         
         const transcribeJobName = `TranscribeJob_${jobId}`;
         await transcribeClient.send(new StartTranscriptionJobCommand({
             TranscriptionJobName: transcribeJobName,
             IdentifyLanguage: true,
             MediaFormat: "mp3",
             Media: { MediaFileUri: `s3://${bucket}/${s3Key}` },
         }));
         
         let transcribeStatus = 'IN_PROGRESS';
         let transcriptUri = '';
         let retries = 0;
         while (transcribeStatus === 'IN_PROGRESS' || transcribeStatus === 'QUEUED') {
             await new Promise(r => setTimeout(r, 5000));
             const jobRes = await transcribeClient.send(new GetTranscriptionJobCommand({ TranscriptionJobName: transcribeJobName }));
             transcribeStatus = jobRes.TranscriptionJob?.TranscriptionJobStatus || 'FAILED';
             
             if (transcribeStatus === 'COMPLETED') {
                 transcriptUri = jobRes.TranscriptionJob?.Transcript?.TranscriptFileUri || '';
                 break;
             }
             if (transcribeStatus === 'FAILED') {
                 throw new Error("ការបកប្រែតាមរយៈ Amazon ទទួលបរាជ័យ: " + jobRes.TranscriptionJob?.FailureReason);
             }
             retries++;
             jobs.set(jobId, { status: 'transcribing with amazon', progress: 50 + Math.min(retries * 2, 35) });
         }
         
         jobs.set(jobId, { status: 'processing results', progress: 85 });
         
         const resultRes = await fetch(transcriptUri);
         const resultJson: any = await resultRes.json();
         
         // Parse resultJson to {id, start, end, text}
         const items = resultJson.results?.items || [];
         let originalLines = [];
         let currentLine = null;
         
         let wordCount = 0;
         for (const item of items) {
             if (item.type === 'pronunciation') {
                 if (!currentLine) {
                     currentLine = { id: Math.random().toString(), start: item.start_time, end: item.end_time, text: item.alternatives[0].content };
                     wordCount = 1;
                 } else {
                     const gap = parseFloat(item.start_time) - parseFloat(currentLine.end);
                     const duration = parseFloat(item.end_time) - parseFloat(currentLine.start);
                     const isPunctuationEnding = currentLine.text.match(/[.!?]$/);
                     
                     // Tighter chunking for perfect lip sync:
                     // 1. Pause > 0.5s
                     // 2. Line duration > 3.5s (don't make sentences too long)
                     // 3. Word count >= 10 words
                     // 4. Sentence ended (punctuation) + slight pause
                     if (gap > 0.5 || duration > 3.5 || wordCount >= 10 || (isPunctuationEnding && gap > 0.2)) {
                         originalLines.push(currentLine);
                         currentLine = { id: Math.random().toString(), start: item.start_time, end: item.end_time, text: item.alternatives[0].content };
                         wordCount = 1;
                     } else {
                         currentLine.end = item.end_time;
                         currentLine.text += " " + item.alternatives[0].content;
                         wordCount++;
                     }
                 }
             } else if (item.type === 'punctuation' && currentLine) {
                 currentLine.text += item.alternatives[0].content;
             }
         }
         if (currentLine) originalLines.push(currentLine);
         
         const rawLines = originalLines.map(line => ({
             id: line.id,
             start: line.start,
             end: line.end,
             text: line.text
         }));
         originalLines = validateSubtitleLines(normalizeSubtitleTimeline(rawLines));
         
         if (originalLines.length === 0) {
             throw new Error("AWS Transcribe មិនអាចស្គាល់សំឡេងបានទេ (No speech detected). អាចដោយសារវីដេអូគ្មានសំឡេង ឬប្រើភាសាដែលប្រព័ន្ធមិនស្គាល់។");
         }

         jobs.set(jobId, { status: 'translating to khmer', progress: 90 });
         console.log(`Translating ${originalLines.length} lines to Khmer...`);
         
         // Translate via Gemini in chunks
         const CHUNK_SIZE = 40;
         let translatedLines = [];
         
         for (let i = 0; i < originalLines.length; i += CHUNK_SIZE) {
             const chunk = originalLines.slice(i, i + CHUNK_SIZE);
             let chunkSuccess = false;
             let generateRetries = 0;
             
             while (!chunkSuccess && generateRetries < 3) {
                 try {
                     const response = await currentAi.models.generateContent({
                         model: activeGeminiModel,
                         contents: [{
                             role: 'user',
                             parts: [
                                 { text: 'You are a professional subtitle translator. Translate the "text" fields in the following JSON array from its original language into Khmer (Cambodian). Keep the exact same JSON structure, keep the "id", "start", and "end" fields exactly the same. Only translate the "text" field. Return ONLY a valid JSON array.\n\n' + JSON.stringify(chunk) }
                             ]
                         }],
                         config: {
                             responseMimeType: 'application/json',
                         }
                     });
                     
                     let responseText = response.text || '';
                     trackTokenUsage(activeGeminiModel, response.usageMetadata);
                     const cleanedResponse = responseText.trim();
                      const parsedChunk = JSON.parse(cleanedResponse);

                      if (!Array.isArray(parsedChunk)) {
                        throw new Error("Gemini translation response is not an array.");
                      }

                      if (parsedChunk.length != chunk.length) {
                        throw new Error(`Gemini returned ${parsedChunk.length} lines, expected ${chunk.length}.`);
                      }

                      const validatedChunk = chunk.map((originalLine, index) =>
                        mergeTranslatedSubtitleLine(
                          validateSubtitleLine(originalLine, index),
                          parsedChunk[index],
                          index
                        )
                      );

                     translatedLines.push(...validatedChunk);
                     chunkSuccess = true;
                 } catch (err) {
                     console.error(`Translation chunk ${i} error:`, err.message);
                     generateRetries++;
                     if (generateRetries >= 3) throw new Error("Translation via Gemini failed after 3 attempts.");
                     await new Promise(r => setTimeout(r, 3000));
                 }
             }
             
             const translateProgress = 90 + Math.floor((i / originalLines.length) * 10);
             const percent = Math.floor(Math.min(100, ((i + CHUNK_SIZE) / originalLines.length) * 100));
             jobs.set(jobId, { status: `translating (${percent}%)`, progress: Math.min(99, translateProgress) });
         }
         
         // Cleanup S3
         try {
             await s3Client.send(new DeleteObjectCommand({ Bucket: bucket, Key: s3Key }));
         } catch(e) { console.error('Failed to cleanup S3', e); }
         
          const speakers = await extractSpeakerReferenceVoices(filePath, fileId, translatedLines);
          const masterVoices = {
            female: Object.values(speakers).find(s => s.gender === 'female' && s.referenceAudioBase64)?.referenceAudioBase64 || null,
            male: Object.values(speakers).find(s => s.gender === 'male' && s.referenceAudioBase64)?.referenceAudioBase64 || null
          };
           const masterVoiceBase64 = masterVoices.female || masterVoices.male;
           if (masterVoices.female) femaleVoiceCache.set(fileId, masterVoices.female);
           if (masterVoices.male) maleVoiceCache.set(fileId, masterVoices.male);
           if (masterVoiceBase64) masterVoiceCache.set(fileId, masterVoiceBase64);
           if (fs.existsSync(filePath)) trackUploadedVideo(fileId);
           
           jobs.set(jobId, { status: 'done', progress: 100, lines: translatedLines, masterVoiceBase64, masterVoices, speakers });
          return; // Exit here for Amazon
      }
      
      // Upload to Gemini
      console.log(`Uploading file to Gemini... ${uploadPath}`);
      jobs.set(jobId, { status: 'uploading to gemini', progress: 45 });
      
      const fileBuffer = fs.readFileSync(uploadPath);
      const fileBlob = new Blob([fileBuffer]);
      
      const uploadResult = await currentAi.files.upload({ file: fileBlob, config: { mimeType: uploadMime } });
      console.log(`Upload complete. Generating content...`);

      // We may need to poll if it's a large video, but wait for active state
      jobs.set(jobId, { status: 'processing video', progress: 50 });
      let fileState = await currentAi.files.get({ name: uploadResult.name });
      let retries = 0;
      while (fileState.state === 'PROCESSING' && retries < 40) {
        console.log('File is processing, waiting...');
        await new Promise(r => setTimeout(r, 3000));
        fileState = await currentAi.files.get({ name: uploadResult.name });
        retries++;
        jobs.set(jobId, { status: 'processing video', progress: 50 + Math.min(retries * 2, 20) });
      }

      if (fileState.state === 'FAILED') {
        throw new Error('Video processing failed on Gemini side.');
      }

      jobs.set(jobId, { status: 'generating subtitles', progress: 75 });
      let response;
      let generateRetries = 0;
      let generateSuccess = false;
      let lastError;

      while (!generateSuccess && generateRetries < 3) {
        try {
          if (generateRetries > 0) {
            console.log(`Retrying generation (Attempt ${generateRetries + 1})...`);
            jobs.set(jobId, { status: `retrying generation (${generateRetries}/3)`, progress: 75 });
            await new Promise(resolve => setTimeout(resolve, 5000 * generateRetries)); // Exponential-ish backoff
          }
          
          response = await currentAi.models.generateContent({
            model: activeGeminiModel,
            contents: [
              {
                role: 'user',
                parts: [
                  { text: `You are an expert professional subtitle transcriber and translator.

TASK:
Listen to and process the ENTIRE audio/video from beginning to end. Do NOT summarize the content.

TRANSCRIPTION AND SEGMENTATION RULES:
1. Capture EVERY spoken dialogue and do not omit, summarize, or paraphrase any speech.
2. Preserve the actual chronological order of all speech.
3. Create MANY short sequential subtitle segments following natural speech phrases.
4. Prefer approximately 1-6 seconds per subtitle segment when speech allows.
5. Split long sentences into multiple subtitle segments at natural pauses or phrase boundaries.
6. Do NOT combine multiple separate sentences or long dialogue into one subtitle.
7. Do NOT create only a small number of large subtitle blocks.
8. Each subtitle must have accurate start and end timestamps based on the actual audio.
9. Timestamps must cover the complete spoken content throughout the video, not just the beginning.
10. Continue processing until the END of the audio/video.
11. If there are pauses or silence, do not invent dialogue during silence.
12. If multiple people speak, preserve the chronological sequence of their speech.
13. Perform SPEAKER DIARIZATION: Identify and assign a consistent speaker ID ("speaker_001", "speaker_002", "speaker_003", etc.) and speakerName (e.g. "Speaker 1 (ដុងយី)", "Speaker 2 (ព្រះរាជា)") for each dialogue. Maintain speaker consistency across the video.
14. For each spoken dialogue, determine the speaker's vocal gender as "female" or "male".
15. ALL subtitle text must be translated into natural Khmer (Cambodian).
16. Do NOT output the original-language transcript.
17. Do NOT summarize.

IMPORTANT:
The video may be several minutes long. Do NOT reduce the entire video to a small number of subtitle entries simply to save tokens. Produce as many accurate subtitle segments as reasonably possible.

OUTPUT:
Return ONLY a valid JSON array.
Each object MUST use exactly this schema:
{ id: string, start: string, end: string, text: string, gender: "female" | "male", speaker: string, speakerName: string }

Use timestamp format M:SS.S or MM:SS.S.
IDs must be sequential: 1, 2, 3, 4, ...
Do not output markdown or explanations.
Do not output an empty array unless there is absolutely no speech.` },
                  { fileData: { fileUri: uploadResult.uri, mimeType: uploadMime } }
                ]
              }
            ],
            config: {
              responseMimeType: 'application/json',
              responseSchema: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    id: { type: Type.STRING },
                    start: { type: Type.STRING },
                    end: { type: Type.STRING },
                    text: { type: Type.STRING },
                    gender: { type: Type.STRING },
                    speaker: { type: Type.STRING },
                    speakerName: { type: Type.STRING }
                  },
                  required: ["id", "start", "end", "text"]
                }
              }
            }
          });
          generateSuccess = true;
        } catch (e: any) {
          lastError = e;
          console.error(`Generation error (Attempt ${generateRetries + 1}):`, e.message);
          if (e.message?.includes('503') || e.message?.includes('429') || e.message?.includes('UNAVAILABLE') || e.message?.includes('RESOURCE_EXHAUSTED')) {
            generateRetries++;
          } else {
            throw e; // Break loop for non-transient errors
          }
        }
      }

      if (!generateSuccess) {
        throw lastError;
      }

      let responseText = response?.text || '';
      trackTokenUsage(activeGeminiModel, response?.usageMetadata);
      responseText = responseText.replace(/^```json\s*/, '').replace(/\s*```$/, '');
      
      let lines;
      try {
        lines = JSON.parse(responseText);
      } catch (err) {
        // Fallback: try to match array and fix truncation
        const jsonMatch = responseText.match(/\[\s*\{[\s\S]*/);
        if (jsonMatch) {
          let fixedStr = jsonMatch[0];
          const lastClose = fixedStr.lastIndexOf('}');
          if (lastClose !== -1) {
             fixedStr = fixedStr.substring(0, lastClose + 1) + ']';
             try {
                lines = JSON.parse(fixedStr);
             } catch (e2) {
                throw new Error('Could not parse JSON from Gemini response: ' + responseText);
             }
          } else {
             throw new Error('Could not parse JSON from Gemini response: ' + responseText);
          }
        } else {
          throw new Error('Could not parse JSON from Gemini response: ' + responseText);
        }
      }

      const normalizedLines = normalizeSubtitleTimeline(lines);
      const validatedLines = validateSubtitleLines(normalizedLines);
      
      // Clean up and extract speaker reference voices for consistent TTS voice cloning
      const speakers = await extractSpeakerReferenceVoices(filePath, fileId, validatedLines);
      const masterVoices = {
        female: Object.values(speakers).find(s => s.gender === 'female' && s.referenceAudioBase64)?.referenceAudioBase64 || null,
        male: Object.values(speakers).find(s => s.gender === 'male' && s.referenceAudioBase64)?.referenceAudioBase64 || null
      };
      const masterVoiceBase64 = masterVoices.female || masterVoices.male;
      if (masterVoices.female) femaleVoiceCache.set(fileId, masterVoices.female);
      if (masterVoices.male) maleVoiceCache.set(fileId, masterVoices.male);
      if (masterVoiceBase64) masterVoiceCache.set(fileId, masterVoiceBase64);
      if (fs.existsSync(filePath)) trackUploadedVideo(fileId);
      try {
        await currentAi.files.delete({ name: uploadResult.name });
      } catch(e) {
        console.error('Failed to delete from Gemini', e);
      }

      jobs.set(jobId, { status: 'done', progress: 100, lines: validatedLines, masterVoiceBase64, masterVoices, speakers });
    } catch (error: any) {
      console.error('Transcription error:', error);
      let errorMessage = error.message;
      if (errorMessage?.includes('429') || errorMessage?.includes('Quota exceeded') || errorMessage?.includes('RESOURCE_EXHAUSTED')) {
        errorMessage = 'ប្រព័ន្ធ AI របស់ Google កំពុងរវល់ ឬអស់ចំនួនប្រើប្រាស់ឥតគិតថ្លៃ។ សូមរង់ចាំប្រហែល 1 នាទីរួចសាកល្បងម្តងទៀត ឬបញ្ចូល API Key ផ្ទាល់ខ្លួនរបស់អ្នក។ (Rate Limit 429)';
      } else if (errorMessage?.includes('503') || errorMessage?.includes('UNAVAILABLE') || errorMessage?.includes('high demand')) {
        errorMessage = 'ប្រព័ន្ធ AI របស់ Google កំពុងមានអ្នកប្រើប្រាស់ច្រើន (High Demand/503) ធ្វើឱ្យការបកប្រែបរាជ័យ។ សូមរង់ចាំបន្តិចរួចចុចសាកល្បងម្តងទៀត។';
      } else if (errorMessage?.includes('504') || errorMessage?.includes('DEADLINE_EXCEEDED')) {
        errorMessage = 'វីដេអូវែងពេកធ្វើឱ្យការបកប្រែចំណាយពេលយូរហួសកំណត់ (Timeout)។ សូមសាកល្បងជាមួយវីដេអូខ្លីជាងនេះ ឬព្យាយាមម្តងទៀតនៅពេលក្រោយ។';
      }
      jobs.set(jobId, { status: 'error', progress: 0, error: errorMessage });
    }
  })();
});

app.post('/api/test-aws', async (req, res) => {
    try {
        const reqAwsAccessKeyId = typeof req.headers['x-aws-access-key-id'] === 'string' ? req.headers['x-aws-access-key-id'] : '';
        const reqAwsSecretAccessKey = typeof req.headers['x-aws-secret-access-key'] === 'string' ? req.headers['x-aws-secret-access-key'] : '';
        const reqAwsRegion = typeof req.headers['x-aws-region'] === 'string' ? req.headers['x-aws-region'] : 'ap-southeast-2';
        const reqAwsS3Bucket = typeof req.headers['x-aws-s3-bucket'] === 'string' ? req.headers['x-aws-s3-bucket'] : '';

        if (!reqAwsAccessKeyId || !reqAwsSecretAccessKey || !reqAwsS3Bucket) {
            return res.status(400).json({ error: 'សូមបំពេញ AWS Keys និង S3 Bucket ឱ្យបានពេញលេញសិន' });
        }

        const awsConfig = {
            region: reqAwsRegion,
            credentials: {
                accessKeyId: reqAwsAccessKeyId,
                secretAccessKey: reqAwsSecretAccessKey
            }
        };

        const s3Client = new S3Client(awsConfig);
        
        // Try to list objects in the bucket to test credentials and bucket access
        const testCommand = new ListObjectsV2Command({ Bucket: reqAwsS3Bucket, MaxKeys: 1 });
        await s3Client.send(testCommand);

        res.json({ success: true, message: 'AWS Keys និង Bucket របស់អ្នកត្រឹមត្រូវ អាចប្រើបាន!' });
    } catch (e) {
        console.error('AWS Test Error:', e);
        res.status(400).json({ error: 'បញ្ហាភ្ជាប់ទៅ AWS: ' + e.message });
    }
});

app.get('/api/debug/jobs', (req, res) => {
    const allJobs = {};
    for (const [k, v] of jobs.entries()) {
        allJobs[k] = { status: v.status, progress: v.progress, error: v.error, linesCount: v.lines ? v.lines.length : 0 };
    }
    res.json(allJobs);
});

// Token usage tracking endpoints
app.get('/api/token-usage', (req, res) => {
  res.json({
    totalPromptTokens: tokenUsageTracker.totalPromptTokens,
    totalCandidatesTokens: tokenUsageTracker.totalCandidatesTokens,
    totalTokens: tokenUsageTracker.totalTokens,
    callCount: tokenUsageTracker.callCount,
    lastModel: tokenUsageTracker.lastModel,
    lastUpdated: tokenUsageTracker.lastUpdated,
    recentHistory: tokenUsageTracker.history.slice(-20)
  });
});

app.post('/api/token-usage/reset', (req, res) => {
  tokenUsageTracker.totalPromptTokens = 0;
  tokenUsageTracker.totalCandidatesTokens = 0;
  tokenUsageTracker.totalTokens = 0;
  tokenUsageTracker.callCount = 0;
  tokenUsageTracker.lastModel = '';
  tokenUsageTracker.lastUpdated = null;
  tokenUsageTracker.history = [];
  res.json({ success: true });
});



app.get('/api/transcribe/status', (req, res) => {
  const jobId = req.query.jobId as string;
  const job = jobs.get(jobId);
  if (!job) {
    return res.status(404).json({ error: 'Job not found' });
  }
  res.json(job);
});

app.post('/api/tts', async (req, res) => {
  try {
    const {
      text,
      voice,
      fileId,
      startTime,
      endTime,
      start,
      end,
      gender,
      speakerId,
      speaker,
      referenceAudioBase64,
      promptText,
      refText
    } = req.body;

    if (typeof text !== 'string' || text.trim().length === 0) {
      return res.status(400).json({ error: 'TTS text is required' });
    }

    if (voice === 'VoxCPM2') {
      let tempRefFile: string | null = null;
      try {
        let refBase64: string | null = null;
        let promptAudioText: string | null = null;

        // Priority 1: Direct reference audio supplied by client (Speaker Voice or custom audio)
        if (typeof referenceAudioBase64 === 'string' && referenceAudioBase64.length > 500) {
          refBase64 = referenceAudioBase64;
          if (typeof promptText === 'string') promptAudioText = promptText;
          else if (typeof refText === 'string') promptAudioText = refText;
        }

        // Priority 2: Speaker-specific reference voice from video diarization mapping
        const spkKey = speakerId || speaker;
        if (!refBase64 && fileId && spkKey && speakerVoiceCache.has(`${fileId}_${spkKey}`)) {
          refBase64 = speakerVoiceCache.get(`${fileId}_${spkKey}`) || null;
          const profiles = speakerProfileCache.get(fileId);
          if (profiles && profiles[spkKey]?.refText) {
            promptAudioText = profiles[spkKey].refText || null;
          }
        }

        // Priority 3: Fallback to gender-matched cache from video
        if (!refBase64 && fileId) {
          if (gender === 'female' && femaleVoiceCache.has(fileId)) {
            refBase64 = femaleVoiceCache.get(fileId) || null;
          } else if (gender === 'male' && maleVoiceCache.has(fileId)) {
            refBase64 = maleVoiceCache.get(fileId) || null;
          }
        }

        // Priority 4: Fallback to general master voice from video
        if (!refBase64 && fileId && masterVoiceCache.has(fileId)) {
          refBase64 = masterVoiceCache.get(fileId) || null;
        }

        let voxcpmBaseUrl = process.env.VOXCPM_API_URL;
        if (!voxcpmBaseUrl) {
          voxcpmBaseUrl = process.env.RENDER ? 'http://54.254.244.148/voxcpm' : 'http://127.0.0.1:5005';
        }

        const payload: any = {
          text,
          reference_audio_base64: refBase64,
          inference_timesteps: 6,
          cfg_value: 2.0
        };
        if (gender) {
          payload.gender = gender;
        }

        let response: any;
        try {
          response = await fetch(`${voxcpmBaseUrl}/clone`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
          });
        } catch (fetchErr: any) {
          if (voxcpmBaseUrl !== 'http://54.254.244.148/voxcpm') {
            console.warn(`[TTS VoxCPM2] Failed connecting to ${voxcpmBaseUrl} (${fetchErr.message}), falling back to http://54.254.244.148/voxcpm...`);
            response = await fetch('http://54.254.244.148/voxcpm/clone', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(payload)
            });
          } else {
            throw fetchErr;
          }
        }

        if (!response.ok) {
          const errBody = await response.text();
          throw new Error(`VoxCPM2 Service Error (${response.status}): ${errBody}`);
        }

        const durationHeader = response.headers.get('X-TTS-Duration');
        const audioBuffer = Buffer.from(await response.arrayBuffer());
        const contentType = response.headers.get('Content-Type') || 'audio/mpeg';

        res.set('Content-Type', contentType);
        if (durationHeader) {
          res.set('X-TTS-Duration', durationHeader);
        } else {
          const tempOut = path.join(os.tmpdir(), `vox_${crypto.randomUUID()}.mp3`);
          fs.writeFileSync(tempOut, audioBuffer);
          const probed = await probeAudio(tempOut);
          fs.unlinkSync(tempOut);
          res.set('X-TTS-Duration', probed.duration.toFixed(3));
        }

        return res.send(audioBuffer);
      } finally {
        if (tempRefFile && fs.existsSync(tempRefFile)) {
          try { fs.unlinkSync(tempRefFile); } catch (e) {}
        }
      }
    }
    
    const targetVoice = (gender === 'female' || (!gender && voice === 'Sreymom')) ? 'km-KH-SreymomNeural' : 'km-KH-PisethNeural';
    
    const tts = new EdgeTTS({ voice: targetVoice, lang: 'km-KH' });
    
    const tempFile = path.join(os.tmpdir(), `tts_${crypto.randomUUID()}.mp3`);
    await tts.ttsPromise(text, tempFile);

    const probed = await probeAudio(tempFile);
    const audioBuffer = fs.readFileSync(tempFile);
    fs.unlinkSync(tempFile);
    
    res.set('Content-Type', 'audio/mpeg');
    res.set('X-TTS-Duration', probed.duration.toFixed(3));
    res.send(audioBuffer);
  } catch (error: any) {
    console.error('TTS Error:', error);
    res.status(500).json({ error: error.message });
  }
});


app.post('/api/export-video', upload.any(), async (req, res) => {
  try {
    const files = req.files as Express.Multer.File[] || [];
    const srtFile = files.find(f => f.fieldname === 'srt');
    
    // Hash inputs for caching
    const metadataValue = req.body.metadata;
    const metadataStr = typeof metadataValue === 'string' ? metadataValue : '';
    const videoFileId = req.body.videoFileId || '';
    const srtContent = srtFile && fs.existsSync(srtFile.path) ? fs.readFileSync(srtFile.path, 'utf8') : '';
    
const hash = crypto.createHash('sha256');
    hash.update(videoFileId);
    hash.update(metadataStr);
    hash.update(srtContent);
    // Include audio file sizes to detect if an audio file was regenerated
    const audioFilesForHash = files.filter(f => f.fieldname.startsWith('audio_'));
    audioFilesForHash.sort((a, b) => a.fieldname.localeCompare(b.fieldname));
    for (const af of audioFilesForHash) {
        if (fs.existsSync(af.path)) {
            hash.update(fs.statSync(af.path).size.toString());
        }
    }
    const exportKey = hash.digest('hex');
    
    if (exportCache.has(exportKey)) {
        const existingJobId = exportCache.get(exportKey);
        const job = exportJobs.get(existingJobId!);
        if (job && (job.status === 'completed' || job.status === 'processing') && job.path && fs.existsSync(job.path)) {
            // Cleanup incoming files since we are using cache
            files.forEach(f => {
              try { fs.unlinkSync(f.path); } catch (e) {}
            });
            // Cleanup incoming chunks
            const videoTotalChunks = parseInt(req.body.videoTotalChunks || '0', 10);
            for (let i = 0; i < videoTotalChunks; i++) {
              const chunkPath = path.join(os.tmpdir(), `upload_${videoFileId}_part_${i}`);
              if (fs.existsSync(chunkPath)) fs.unlinkSync(chunkPath);
            }
            return res.json({ jobId: existingJobId, cached: true });
        }
    }
    let videoPath = '';
    const videoTotalChunks = parseInt(req.body.videoTotalChunks || '0', 10);
    
    if (videoFileId && videoTotalChunks > 0) {
      videoPath = path.join(os.tmpdir(), `upload_${videoFileId}`);
      if (fs.existsSync(videoPath)) {
        fs.unlinkSync(videoPath);
      }
      for (let i = 0; i < videoTotalChunks; i++) {
        const chunkPath = path.join(os.tmpdir(), `upload_${videoFileId}_part_${i}`);
        if (!fs.existsSync(chunkPath)) {
          throw new Error(`Missing chunk ${i} for export`);
        }
        const chunkData = fs.readFileSync(chunkPath);
        fs.appendFileSync(videoPath, chunkData);
        fs.unlinkSync(chunkPath);
      }
      trackUploadedVideo(videoFileId);
    } else if (videoFileId) {
      const existingPath = path.join(os.tmpdir(), `upload_${videoFileId}`);
      if (fs.existsSync(existingPath) && fs.statSync(existingPath).size > 0) {
        videoPath = existingPath;
        trackUploadedVideo(videoFileId);
      }
    }
    if (!videoPath) {
      const videoFile = files.find(f => f.fieldname === 'video');
      if (videoFile) {
        videoPath = videoFile.path;
      } else {
        throw new Error('Missing video file');
      }
    }
    
    let audioMetadata: AudioSegmentMetadata[] = [];
    if (metadataStr) {
      audioMetadata = validateExportAudioMetadata(JSON.parse(metadataStr));
    }
    
    const jobId = Date.now().toString();
    exportCache.set(exportKey, jobId);
    const outputVideoPath = path.join(process.cwd(), "outputs", `output_${jobId}.mp4`);
    fs.mkdirSync(path.dirname(outputVideoPath), { recursive: true });
    
    exportJobs.set(jobId, { status: 'processing' });
    res.json({ jobId });
    
    // Process in background
    (async () => {
      let currentCmd = '';
      let tempOutputVideoPath = '';
      let finalSrtPath = '';
      let finalAssPath = '';
      try {
        let hasOriginalAudio = false;
        let originalAudioStreamCount = 0;
        let videoDuration = 0;
        try {
          currentCmd = `ffprobe -v error -select_streams a -show_entries stream=index -of csv=p=0 "${videoPath}"`;
          const { stdout } = await execAsync(currentCmd);
          originalAudioStreamCount = stdout.trim().split('\n').filter(Boolean).length;
          hasOriginalAudio = originalAudioStreamCount > 0;
        } catch(e) {
          logFfmpegDiagnostic('ffprobe (check original audio)', currentCmd, e, e.stderr, e.stdout);
        }
        try {
          currentCmd = `ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "${videoPath}"`;
          const { stdout } = await execAsync(currentCmd);
          videoDuration = Number(stdout.trim()) || 0;
        } catch(e) {
          logFfmpegDiagnostic('ffprobe (video duration)', currentCmd, e, e.stderr, e.stdout);
        }
        if (videoDuration <= 0) {
          throw new Error('Export validation failed: invalid video duration');
        }

        let videoWidth = 0;
        let videoHeight = 0;
        let videoFps = 0;
        try {
          currentCmd = `ffprobe -v error -select_streams v:0 -show_entries stream=width,height,r_frame_rate -of csv=p=0 "${videoPath}"`;
          const { stdout } = await execAsync(currentCmd);
          const parts = stdout.trim().split(',');
          videoWidth = Number(parts[0]) || 0;
          videoHeight = Number(parts[1]) || 0;
          if (parts[2]) {
            const [num, den] = parts[2].split('/').map(Number);
            videoFps = den ? (num / den) : Number(parts[2]) || 0;
          }
        } catch(e) {
          logFfmpegDiagnostic('ffprobe (video dimensions/fps)', currentCmd, e, e.stderr, e.stdout);
        }

        const renderedSegments = await buildRenderedAudioSegments(files, audioMetadata, videoDuration);
        validateSegmentTimeline(renderedSegments, videoDuration);
        for (const segment of renderedSegments) {
          console.log(
            `[AUDIO SEGMENT] order=${segment.renderOrder} ` +
            `key=${segment.key} segmentId=${segment.metadata.segmentId ?? 'unspecified'} ` +
            `speakerId=${segment.metadata.speakerId ?? 'unspecified'} ` +
            `voiceId=${segment.metadata.voiceId ?? 'unspecified'} ` +
            `sourceStart=${formatSeconds(segment.startSeconds)}s ` +
            `sourceEnd=${formatSeconds(segment.endSeconds)}s ` +
            `ttsDuration=${formatSeconds(segment.ttsDuration)}s ` +
            `file=${path.basename(segment.path)} ` +
            `placement=${formatSeconds(segment.placementSeconds)}s rate=${segment.rate.toFixed(3)}`
          );
        }

        let finalMapA = '';
        const tempMixedAudio = path.join(os.tmpdir(), `mixed_${jobId}.m4a`);
        
        // STEP 1: Mix validated TTS and the original bed audio exactly once.
        if (renderedSegments.length > 0) {
           let mixCmd = `ffmpeg -nostdin -hide_banner -threads 0 -loglevel error`;
           let audioFilter = '';
           let mixInputs = '';
           let inputCount = renderedSegments.length;
           let mixDurationMode = 'longest';
           
           if (hasOriginalAudio) {
               mixCmd += ` -vn -i "${videoPath}"`;
               audioFilter += `[0:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo,volume=0.1[a0]; `;
               mixInputs += `[a0]`;
               mixDurationMode = 'first';
               inputCount += 1;
           }
           
           renderedSegments.forEach((segment, index) => {
              const inputIndex = hasOriginalAudio ? index + 1 : index;
              mixCmd += ` -i "${segment.path}"`;
              const delayMs = Math.round(segment.placementSeconds * 1000);
              const atempo = buildAtempoFilter(segment.rate);
              const rate = atempo ? `,${atempo}` : '';
              audioFilter +=
                `[${inputIndex}:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo${rate},` +
                `adelay=${delayMs}|${delayMs}[a${inputIndex}]; `;
              mixInputs += `[a${inputIndex}]`;
           });
           
           if (inputCount === 1) { 
              audioFilter += `${mixInputs}aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo[aout]`; 
           } else { 
              audioFilter += `${mixInputs}amix=inputs=${inputCount}:duration=${mixDurationMode}:dropout_transition=0:normalize=0[aout]`;
           }
           
           mixCmd += ` -filter_complex "${audioFilter}" -map "[aout]" -c:a aac -ar 44100 -ac 2 -b:a 192k -threads 0 -y "${tempMixedAudio}"`;
           console.log('Running FFmpeg audio mix:', mixCmd);
           let mixResult;
           try {
               currentCmd = mixCmd;
               mixResult = await execAsync(mixCmd);
               if (mixResult.stderr) logFfmpegDiagnostic('ffmpeg (audio mix warning)', mixCmd, null, mixResult.stderr, mixResult.stdout);
           } catch(e) {
               logFfmpegDiagnostic('ffmpeg (audio mix failure)', mixCmd, e, e.stderr, e.stdout);
               throw new Error('FFmpeg mix error: ' + (e.stderr || e.message).substring(0, 500));
           }
           
           finalMapA = buildFinalAudioMap(hasOriginalAudio, renderedSegments);
        } else if (hasOriginalAudio) {
           finalMapA = '0:a';
        }
        // STEP 2: Burn the uploaded SRT into the video stream and export
        // exactly one intended audio stream. Subtitle burn-in requires a
        // video re-encode; video copying cannot apply a video filter.
        const hasSubtitles = Boolean(srtFile && srtContent.trim());
        let videoFilter = '';
        let mapV = '0:v';

        finalSrtPath = srtFile ? srtFile.path : '';
        if (srtFile && !finalSrtPath.endsWith('.srt')) {
          const srtWithExt = `${finalSrtPath}.srt`;
          try {
            fs.copyFileSync(finalSrtPath, srtWithExt);
            finalSrtPath = srtWithExt;
          } catch (e) {}
        }
        if (finalSrtPath && fs.existsSync(finalSrtPath)) {
          try {
            const rawContent = fs.readFileSync(finalSrtPath, 'utf8');
            const srtLines = rawContent.split(/\r?\n/);
            const formattedSrt = srtLines.map(line => {
              if (/^\d+$/.test(line.trim()) || line.includes('-->')) {
                return line;
              }
              return formatKhmerSubtitleText(line);
            }).join('\n');
            fs.writeFileSync(finalSrtPath, formattedSrt, 'utf8');
          } catch (e) {
            console.error('Failed to format subtitle line wrapping:', e);
          }
        }

        if (hasSubtitles) {
          let scaleFilter = '';
          let targetWidth = videoWidth;
          let targetHeight = videoHeight;
          if (videoWidth > 0 && videoHeight > 0) {
            const isPortrait = videoHeight > videoWidth;
            if (!isPortrait && videoHeight > 720) {
              scaleFilter = 'scale=-2:720,';
              targetHeight = 720;
              targetWidth = Math.round((videoWidth * 720) / videoHeight);
              if (targetWidth % 2 !== 0) targetWidth -= 1;
            } else if (isPortrait && videoWidth > 720) {
              scaleFilter = 'scale=720:-2,';
              targetWidth = 720;
              targetHeight = Math.round((videoHeight * 720) / videoWidth);
              if (targetHeight % 2 !== 0) targetHeight -= 1;
            }
          }
          let fpsFilter = '';
          if (videoFps > 30) {
            fpsFilter = 'fps=30,';
          }

          if (finalSrtPath && fs.existsSync(finalSrtPath)) {
            try {
              const rawSrt = fs.readFileSync(finalSrtPath, 'utf8');
              const assContent = convertSrtToAss(rawSrt, targetWidth || 1280, targetHeight || 720);
              finalAssPath = path.join(path.dirname(finalSrtPath), `subtitles_${jobId}.ass`);
              fs.writeFileSync(finalAssPath, assContent, 'utf8');
            } catch (err) {
              console.error('Failed to convert SRT to ASS, falling back to buildSubtitleVideoFilter:', err);
            }
          }

          const subFilter = (finalAssPath && fs.existsSync(finalAssPath))
            ? buildAssVideoFilter(finalAssPath)
            : buildSubtitleVideoFilter(finalSrtPath);

          videoFilter = `${scaleFilter}${fpsFilter}${subFilter}`;
          mapV = '[vout]';
        }

        let videoCmd = `ffmpeg -nostdin -hide_banner -threads 0 -loglevel info -i "${videoPath}"`;
        if (renderedSegments.length > 0) {
            videoCmd += ` -i "${tempMixedAudio}"`;
        }

        if (hasSubtitles) {
            videoCmd += ` -filter_complex "${videoFilter}[vout]"`;
        }

        videoCmd += ` -map "${mapV}"`;
        if (finalMapA) {
            videoCmd += ` -map "${finalMapA}"`;
        }

        videoCmd += hasSubtitles
            ? ' -c:v libx264 -preset ultrafast -crf 23 -pix_fmt yuv420p -threads 0'
            : ' -c:v copy';
        if (finalMapA) {
            videoCmd += ` -c:a aac -ar 44100 -ac 2 -b:a 192k`;
        }
        if (videoDuration > 0) {
            videoCmd += ` -t ${videoDuration.toFixed(3)}`;
        }
        videoCmd += ' -movflags +faststart';
        videoCmd += ` -y "${outputVideoPath}"`;
        

        console.log('Running FFmpeg video export:', videoCmd);
        tempOutputVideoPath = path.join(path.dirname(outputVideoPath), `.final_${jobId}.tmp.mp4`);
        videoCmd = videoCmd.replace(`"${outputVideoPath}"`, `"${tempOutputVideoPath}"`);
        
        // Export progress: 50% -> 90% based on real FFmpeg time.
        // Progress is monotonic and can never move backwards.
        exportJobs.set(jobId, { status: 'processing', progress: 50 });

        let exportDuration = 0;
        try {
            const durationCmd = `ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "${videoPath}"`;
            const { stdout: durationOut } = await execAsync(durationCmd);
            exportDuration = Number(durationOut.trim()) || 0;
        } catch (e) {
            exportDuration = 0;
        }

        let lastExportProgress = 50;

        await new Promise((resolve, reject) => {
            const child = spawn(videoCmd, { shell: true });

            let ffmpegOutputBuffer = '';

            child.stderr.on('data', (data) => {
                ffmpegOutputBuffer += data.toString();

                // Keep a bounded buffer so partial stderr chunks are handled safely.
                if (ffmpegOutputBuffer.length > 20000) {
                    ffmpegOutputBuffer = ffmpegOutputBuffer.slice(-10000);
                }

                // Find the latest FFmpeg time=HH:MM:SS.xx value.
                const matches = [
                    ...ffmpegOutputBuffer.matchAll(/time=(\d+):(\d+):(\d+\.\d+)/g)
                ];

                if (matches.length > 0 && exportDuration > 0) {
                    const match = matches[matches.length - 1];

                    const currentTime =
                        Number(match[1]) * 3600 +
                        Number(match[2]) * 60 +
                        Number(match[3]);

                    const ffmpegPercent = Math.min(
                        100,
                        (currentTime / exportDuration) * 100
                    );

                    // Map FFmpeg 0-100% to UI 50-90%.
                    const calculatedProgress = Math.min(
                        90,
                        50 + Math.floor(ffmpegPercent * 0.40)
                    );

                    // Progress must NEVER move backwards.
                    if (calculatedProgress > lastExportProgress) {
                        lastExportProgress = calculatedProgress;

                        exportJobs.set(jobId, {
                            status: 'processing',
                            progress: calculatedProgress
                        });
                    }
                }
            });

            child.on('close', (code) => {
                if (code === 0) {
                    exportJobs.set(jobId, {
                        status: 'processing',
                        progress: 90
                    });
                    resolve(true);
                } else {
                    reject(new Error('FFmpeg exited with code ' + code));
                }
            });

            child.on('error', reject);
        });
        
        // Validate the rendered file before publishing it.
        currentCmd = `ffprobe -v error -show_entries format=duration,size:stream=index,codec_type,codec_name,sample_rate,channels -of json "${tempOutputVideoPath}"`;
        try {
          const { stdout: probeOut } = await execAsync(currentCmd);
          const probe = JSON.parse(probeOut);
          const duration = Number(probe?.format?.duration);
          const size = Number(probe?.format?.size);
          const streams = Array.isArray(probe?.streams) ? probe.streams : [];
          const videoStreams = streams.filter((stream: any) => stream.codec_type === 'video');
          const audioStreams = streams.filter((stream: any) => stream.codec_type === 'audio');
          const audioStream = audioStreams[0];
          
          if (!duration || duration <= 0 || !size || size <= 0) {
              throw new Error('Export validation failed: invalid duration or size');
          }
          if (videoStreams.length !== 1) {
              throw new Error(`Export validation failed: expected 1 video stream, found ${videoStreams.length}`);
          }
          if (finalMapA && audioStreams.length !== 1) {
              throw new Error(`Export validation failed: expected 1 audio stream, found ${audioStreams.length}`);
          }
          if (finalMapA && (Number(audioStream?.sample_rate) !== 44100 || Number(audioStream?.channels) !== 2)) {
              throw new Error('Export validation failed: audio must be stereo 44.1 kHz');
          }
          if (Math.abs(duration - videoDuration) > 1.5) {
              throw new Error(`Export validation failed: output duration changed (expected ${videoDuration}s, got ${duration}s)`);
          }
        } catch (e) {
          logFfmpegDiagnostic('ffprobe (validate output)', currentCmd, e, e.stderr, e.stdout);
          throw e;
        }
        
        try {
          fs.renameSync(tempOutputVideoPath, outputVideoPath);
        } catch (renameErr) {
          fs.copyFileSync(tempOutputVideoPath, outputVideoPath);
          try { fs.unlinkSync(tempOutputVideoPath); } catch (e) {}
        }
        exportJobs.set(jobId, { status: 'completed', path: outputVideoPath, progress: 100 });

        files.forEach(f => {
          try { fs.unlinkSync(f.path); } catch (e) {}
        });
        if (finalSrtPath && finalSrtPath !== srtFile?.path) {
          try { fs.unlinkSync(finalSrtPath); } catch (e) {}
        }
        if (finalAssPath && fs.existsSync(finalAssPath)) {
          try { fs.unlinkSync(finalAssPath); } catch (e) {}
        }
        try { fs.unlinkSync(tempMixedAudio); } catch (e) {}
        if (videoFileId) {
          trackUploadedVideo(videoFileId);
        }

        
      } catch (err: any) {
        logFfmpegDiagnostic('ffmpeg (video export or overall failure)', currentCmd, err, err.stderr, err.stdout);
        exportJobs.set(jobId, { status: 'error', error: `FFMPEG_ERROR: ${err.stderr ? err.stderr.toString().substring(0, 200) : err.message}` });
        
        // Try cleanup
        try { if (fs.existsSync(tempOutputVideoPath)) fs.unlinkSync(tempOutputVideoPath); } catch (e) {}
        if (finalSrtPath && finalSrtPath !== srtFile?.path) {
          try { fs.unlinkSync(finalSrtPath); } catch (e) {}
        }
        if (finalAssPath && fs.existsSync(finalAssPath)) {
          try { fs.unlinkSync(finalAssPath); } catch (e) {}
        }
        files.forEach(f => {
          try { fs.unlinkSync(f.path); } catch (e) {}
        });
        if (videoFileId) {
          trackUploadedVideo(videoFileId);
        }
      }
    })();
  } catch (err: any) {
    console.error('Export upload error:', err);
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/export/status/:jobId', (req, res) => {
  const jobId = req.params.jobId;
  const job = exportJobs.get(jobId);
  if (!job) return res.status(404).json({ error: 'Job not found' });
  res.json(job);
});

app.get('/api/export/download/:jobId', (req, res) => {
  const job = exportJobs.get(req.params.jobId);
  if (!job || !job.path || !fs.existsSync(job.path)) {
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    return res.status(404).send(`
      <script>
        alert("រកមិនឃើញឯកសារវីដេអូទេ។ សូមសាកល្បង Export ម្តងទៀត។ (File not found, server restarted)");
        window.close();
      </script>
    `);
  }
  const filename = (req.query.filename as string) || 'exported_video.mp4';
  res.sendFile(job.path, (err) => {
    // We intentionally don't delete immediately to allow multiple downloads/retries.
  });
});

// Vite middleware for development
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const { createServer: createViteServer } = await import("vite");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
